### ISSUE TITLE
Running WASI binaries

### ISSUE THREAD

**Issue by whitequark** [bytecodealliance/wasmtime-py#1]
Let me start off by saying how much I like wasmtime. I always liked the concept, but six months ago the implementation wasn't quite there. I was pretty sure it'll get better, and today I ran the exact same binary I was trying to run back then in no time and it works better than my most optimistic expectations. Right now it seems like wasmtime is going to solve the single biggest obstacle new [nMigen](https://github.com/nmigen/nmigen) developers encounter, especially on Windows but elsewhere too.

That aside, is there any way I'm missing to run WASI binaries with wasmtime-py? I really only need stdin and stdout, though the [binary I'm interested in](https://github.com/YosysHQ/yosys/pull/1483), I think, is expecting to be able to load from `$PREFIX/share/` so some sort of virtualized fileystem would be ideal.

Is this something I can easily implement myself? (I'm only really familiar with WASM/WASI as a toolchain user, not a library developer.) Or, is it something in scope for wasmtime-py? Do I have to implement every single function WASI provides, or just the ones my application calls?

**Comment by whitequark** [comment]
To answer one of my own questions, it looks like I only need to implement the functions that are actually used, and it doesn't seem very hard! I'm going to leave this open because it looks like the C and Rust embeddings offer built-in WASI bindings, and I'm wondering if Python embedding should, too.

**Comment by whitequark** [comment]
I just read through the docs again and found out that there were, in fact, WASI bindings all this time. I apologize for the disturbance.

**Comment by alexcrichton** [comment]
Thanks for the report! Glad you were able to find an answer, but if anything else comes up don't hesitate to ask!
