### ISSUE TITLE
invalid leading byte (0x3) for component external kind (at offset 0x364cf9)

### ISSUE THREAD

**Issue by JensGM** [bytecodealliance/wasmtime-py#112]
Hey, I'm trying newer versions of the component model and I'm encountering an issue when generating bindings for python. Running the command `python3 -m wasmtime.bindgen build/dynomite.wasm --out-dir build/tmp/py` yields the error

```
RuntimeError: failed to extract interface information from component

Caused by:
    invalid leading byte (0x3) for component external kind (at offset 0x364cf9)
```

@alexcrichton said in https://github.com/bytecodealliance/wasm-tools/issues/842 that this is likely due to a recent binary format change. I do however get the same error using both `wasmtime-py 3.0.0` and main branch (4.0.0). The rest of the tools work, creating the component and creating js bindings with wit-bindgen, but wasmtime.bindgen with python does produce bindings.

**Comment by alexcrichton** [comment]
Can you share the `dynomite.wasm` file?

**Comment by JensGM** [comment]
I'll have to recreate it, but can I send it to you only?

**Comment by JensGM** [comment]
Reinstalled 4.0.0.dev1 from pypi now, and this time, for some reason it works 🤔🤔 I'm confused, but happy, haha. Thanks for the help
