### ISSUE TITLE
AArch64 support

### ISSUE THREAD

**Issue by whitequark** [bytecodealliance/wasmtime-py#12]
There are definitely people [interested](https://twitter.com/ohzee5/status/1263417998104080384) in AArch64 wasmtime-py, but it seems it doesn't work yet.

**Comment by alexcrichton** [comment]
Hm ok so the `--plat-name` of `linux-aarch64` [fails to upload to pypi](https://github.com/bytecodealliance/wasmtime-py/runs/696893740?check_suite_focus=true#step:8:18). It looks to work with `manylinux2014-aarch64` but I wasn't able to install that locally on an AArch64 system. This'll require some more investigation to figure out what to do here.

**Comment by alexcrichton** [comment]
Ok this should be fixed now with https://github.com/bytecodealliance/wasmtime-py/pull/23

**Comment by whitequark** [comment]
Okay, so `manylinux2014_aarch64` is defined in [PEP 599](https://www.python.org/dev/peps/pep-0599/), and `manylinux_2_17_aarch64` (where `2_17` refers to glibc 2.17) is defined in [PEP 600](https://www.python.org/dev/peps/pep-0600/). PEP 600 also [defines](https://www.python.org/dev/peps/pep-0600/#legacy-manylinux-tags) the former to be an exact alias for the latter.

I specified both mostly to be on the safe side; you need the `manylinux2014_aarch64` tag to cover pip versions that don't know what `manylinux_2_17_aarch64` is, and while it's unlikely that we'll see a package manager that _doesn't_ know what `manylinux_2_17_aarch64` is, that's still the tag to use going forward.

I think what you're doing is fine for foreseeable future.
