### ISSUE TITLE
Update wasm tools to 1.0.20

### ISSUE THREAD

**Issue by ivan-kolesar** [bytecodealliance/wasmtime-py#122]
On the latest versions of wit-bindgen, wasm-tools  version of 1.0.20 is used.

Can wasmtime-py be updated to that version as well?

This mis-versions breaks our setup, where we use wasm components for our js and python part of stack.

**Comment by cclauss** [comment]
https://github.com/bytecodealliance/wasm-tools/releases v1.0.27?

**Comment by ivan-kolesar** [comment]
Sorry for late reply, it all works great now.
