### ISSUE TITLE
Ability to set a file-like object (instead of a file path) for stdin and stderr

### ISSUE THREAD

**Issue by simonw** [bytecodealliance/wasmtime-py#123]
I want to use wasmtime-py to run untrusted Python code safely inside a WASM sandbox. Here's the recipe I have so far, thanks to help from @pims https://til.simonwillison.net/webassembly/python-in-a-wasm-sandbox

Part of that recipe is this:

```python
config = WasiConfig()

config.argv = ("python", "-c", code)
config.preopen_dir(".", "/")

with tempfile.TemporaryDirectory() as chroot:
    out_log = os.path.join(chroot, "out.log")
    err_log = os.path.join(chroot, "err.log")
    config.stdout_file = out_log
    config.stderr_file = err_log

    store = Store(linker.engine)

    # Limits how many instructions can be executed:
    store.add_fuel(fuel)
    store.set_wasi(config)
```
Then the code reads from that `out.log` temporary file after executing the code.

It would be much neater if it was possible to pass a file-like object here instead - a `io.BytesIO` or `io.StringIO` for example.

**Comment by simonw** [comment]
@pims [points out](https://hachyderm.io/@pims/109797397508136835) that this can be done using the Go bindings like so:

```go
body := []byte{}
in := bytes.NewReader (body)
out := new(bytes. Buffer) 
stderr := new (bytes.Buffer)

config := wazero.NewModuleConfig().
    WithFS (fs) .
    withstdout (out) . withStdin(in).
    WithStderr(stderr).
    WithName (name).
    WithArgs ("python", "my app-py").
    WithRandSource(rnd)
```

**Comment by pims** [comment]
Minor correction: using a different WASM VM, wazero, as opposed to wasmtime.

**Comment by simonw** [comment]
I just noticed this may be a duplicate of:
- https://github.com/bytecodealliance/wasmtime-py/issues/34

**Comment by simonw** [comment]
Also relevant:
- https://github.com/bytecodealliance/wasmtime/issues/4372
- https://github.com/bytecodealliance/wasmtime-go/issues/34

**Comment by alexcrichton** [comment]
Thanks for the report! I think this is the same as https://github.com/bytecodealliance/wasmtime-py/issues/34 so I'm going to close in favor of that.
