### ISSUE TITLE
limiting execution time

### ISSUE THREAD

**Issue by zeldovich** [bytecodealliance/wasmtime-py#126]
In some cases, an application may want to limit the wall-clock execution time of a wasm module.  The current Python API doesn't quite allow doing this, as far as I can tell.

One natural approach would seem to be to use interruption -- something like

    config.epoch_interruption = True
    store.set_epoch_deadline(1)
    signal.signal(signal.SIGALRM, lambda sig, f: engine.increment_epoch())
    signal.alarm(5)

but it looks like wasmtime masks signals (or perhaps just defers the execution of their Python signal handlers) during module execution.

Another approach might be to use fuel, but it's a bit of a guessing game how much fuel to supply for a particular wall-clock running time bound, and I couldn't find a way to restart a module after it runs out of fuel.

**Comment by alexcrichton** [comment]
You're right that epochs are intended to be used for use cases like this. Typically the epoch increment comes from a different thread in a case like this, although I am not personally all that familiar with how to use threads in Python with ffi and all that. I don't know how well signals work myself, there's nothing specific about wasmtime-py that's masking signals or anything like that and I'm not sure what the consequences are deviating from Python's defaults.

Would it work for your use case to have a thread dedicated for this?

**Comment by zeldovich** [comment]
Thanks for the quick response!  Looking into Python's threading model more, it turns out that my confusion stemmed from not realizing that Python always delivers signals on the main thread, and wasmtime's Python API appears to do the right thing.

One perfectly good solution to my problem is to run the wasmtime module on another thread (e.g., creating one with `threading.Thread().start()`); in this case, the main thread would be free to execute the signal handler, which will interrupt the wasmtime module's execution.

Another perfectly good solution is to avoid the use of signals altogether: one thread can be running the wasmtime module, and another thread can just sleep for some time and then increment the epoch to interrupt.  Since no signals are involved, any of these threads could be Python's main thread.

So, it looks like this was just confusion on my part.  Perhaps someone else might benefit from finding the above explanation of this (non-)issue.

**Comment by alexcrichton** [comment]
Ok cool and  yeah sounds like those strategies should work too!

I should also point out though that I didn't really consider threads much when writing the wasmtime-py bindings for Wasmtime. It's not safe to use a `wasmtime.Store` on multiple threads, for example, but I'm not sure if Python prevents that. For example when an FFI call is made to Wasmtime I don't know if the GIL is held or not. If it's not held (which I think is the case?) then using Wasmtime incorrectly with threads can lead to memory unsafety.

All that being said though the engine type and the increment of epochs is safe to use amongst threads.

**Comment by zeldovich** [comment]
FFI calls through `ctypes.CFUNCTYPE`, which wasmtime-py seems to use, do release the GIL (https://docs.python.org/3/library/ctypes.html#ctypes.CFUNCTYPE), which is useful because it allows for another thread to interrupt by calling `engine.increment_epoch()`, but indeed requires care to avoid other unsafe concurrent operations.

**Comment by alexcrichton** [comment]
Ok makes sense! It sounds like the threads option should work here then so I'm going to close this, but let me know if anything else remains.
