### ISSUE TITLE
Running wasm with shared folder / mapping directory into wasmtime-py

### ISSUE THREAD

**Issue by bivald** [bytecodealliance/wasmtime-py#128]
Hi,

First of all, I'm out of my depth here so please forgive my ignorance :) I'm trying to run wasmtime-py like I would in terminal:

```
wasmtime run --mapdir /::$PWD bin/python-3.11.1.wasm
```

Above is using the [Wasm Runtime Runtime](https://wasmlabs.dev/articles/python-wasm32-wasi/). I've gotten this far:

```
from wasmtime import Store, Module, Engine, WasiConfig, Linker
engine = Engine()
store = Store(engine)
wasi = WasiConfig()
wasi.inherit_argv()
wasi.inherit_env()
wasi.inherit_stdout()
wasi.inherit_stderr()
wasi.inherit_stdin()
store.set_wasi(wasi)
linker = Linker(engine)
linker.define_wasi()
module = Module.from_file(store.engine, 'bin/python-3.11.1.wasm')
linking1 = linker.instantiate(store, module)
start = linking1.exports(store).get("") or linking1.exports(store)["_start"]
start(store)
```

But would need to map a directory into wasm as well. Is this currently possible? (Then I need to figure out how to call the python-wasm32 with input, but that's my next rabbithole)

I understand it looks weird to run python in wasm... from Python, but I'm trying to use it as a Sandbox for untrusted code (if I get a minimal example I'll try to get it running on Google Cloud Functions). The plan is to be able to run the users code "live" in the browser while developing, then running it using wasmtime in the backend once live in my data processing pipeline.

**Comment by alexcrichton** [comment]
I think [`WasiConfig.preopen_dir`](https://bytecodealliance.github.io/wasmtime-py/#wasmtime.WasiConfig.preopen_dir) should cove that use case?

**Comment by bivald** [comment]
I can't believe I missed that. Thank you! 

PS: Unfortunately running in Cloud Functions didn't work, none-approved syscalls :D
