### ISSUE TITLE
NameError: name 'RuntimeValueString' is not defined

### ISSUE THREAD

**Issue by danbev** [bytecodealliance/wasmtime-py#155]
I ran into the following error when trying to extract types into a separate .wit files:
```console
Traceback (most recent call last):
  File "/home/danielbevenius/work/wasm/wasmtime-py/demo-module/demo.py", line 12, in <module>
    main()
  File "/home/danielbevenius/work/wasm/wasmtime-py/demo-module/demo.py", line 8, in main
    ret = wit.something(store)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/danielbevenius/work/wasm/wasmtime-py/demo-module/dist/exports/wit.py", line 27, in something
    variant = RuntimeValueString(list)
              ^^^^^^^^^^^^^^^^^^
NameError: name 'RuntimeValueString' is not defined

```
I've created a [reproducer] for this might help troubleshoot this and the readme contains a note about this perhaps being an issue with a missing module/namespace. The same .wit files work with JavaScript and Rust.

[reproducer]: https://github.com/danbev/wasmtime-py/blob/name-error/demo-module/README.md

**Comment by alexcrichton** [comment]
Thanks for the report! This is probably a mismatch in how variants are represented and how they're lifted, and probably shouldn't be too hard to fix. I don't have time right now myself to tackle this but I'd be happy to review a PR!
