### ISSUE TITLE
unsupported component version: 0xa (at offset 0x0)

### ISSUE THREAD

**Issue by iulian-birlica** [bytecodealliance/wasmtime-py#158]
Hi! I am trying to run `wasmtime.bindgen`on a wasm component generated with `wit-bindgen` and `wit_component::ComponentEncoder`. The code I am testing is from this [repo](https://github.com/MediosZ/component-model-demo). (the repo is not mine, I just found it on the internet).

When trying to run `$ python -m wasmtime.bindgen ./target/component.wasm --out-dir python/markdown/`, I receive the following message:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "...python/3.11.3/lib/python3.11/site-packages/wasmtime/bindgen/__main__.py", line 40, in <module>
    main()
  File "...python/3.11.3/lib/python3.11/site-packages/wasmtime/bindgen/__main__.py", line 30, in main
    files = generate(name, contents)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "...installs/python/3.11.3/lib/python3.11/site-packages/wasmtime/bindgen/__init__.py", line 40, in generate
    raise RuntimeError(result.value)
RuntimeError: failed to extract interface information from component

Caused by:
    unsupported component version: 0xa (at offset 0x0)
```

Everything is the latest version as of now. (wasmtime-py 9.0.0)

**Comment by alexcrichton** [comment]
A component with version 0xa is a relatively old component at this point, so while `wasmtime-py` may be up-to-date at this time you need to make sure that the component itself was also produced by up-to-date tooling.

The example repository you linked is likely using now-outdated tooling for building the component itself which you'll likely need to update to get things working.

**Comment by iulian-birlica** [comment]
I have upgraded everything and generated a new component. I still get an error message, the same one, but with the version `0xd`.

**Comment by alexcrichton** [comment]
Ah apologies but I forgot that the latest wasm-tools suite uses 0xd but the latest Wasmtime, 9.0, uses 0xc. When Wasmtime 10 is released it'll used 0xd but in the meantime when using Wasmtime 9 you'll need to move the tools back a little bit (sorry I forget which versions are involved here in terms of which tools you need to move back and such)

**Comment by guybedford** [comment]
If it helps, `0xc` versions are currently tracked in https://github.com/bytecodealliance/wasm-tools/wiki/Component-Model-Tooling-Compatibility#0xc---component-model-022023---052023.

**Comment by iulian-birlica** [comment]
Would compiling wasmtime-py from source help here? Or has the modification to 0xd not been made yet?

**Comment by iulian-birlica** [comment]
Well, it has now been updated, so I will close this issue.
