### ISSUE TITLE
Troubles with using wasmtime-py in a Python Kivy app on Android

### ISSUE THREAD

**Issue by bingo-V** [bytecodealliance/wasmtime-py#160]
Hello, I'm currently working on an app using the Python Kivy framework, and I'm encountering difficulties while attempting to incorporate wasmtime-py into the project.

Kivy is a cross-platform Python Framework. A kivy app can be built with the Buildozer tool (via Python for Android) to run on Android. 

I want to use wasmtime-py in my kivy app so I compiled the wasmtime source code using the Android NDK to get the libwasmtime.so and then replaced the original `linux-aarch64/_libwasmtime.so` file in wasmtime-py.

During testing, I observed that wasmtime-py works fine for some examples (e.g., the "loader_add" example). But for others, such as those involving stdout, there seems to be some problems. For the "linking" example, although it does not throw any errors, the expected "hello world" output is not displayed.

In addition, I tried to read and write files with a wasm built from Rust. This wasm works fine using wasmtime as runtime, and it can also be invoked using wasmtime-py on MacOS and Ubuntu. However, when the app is packaged for Android, it fails to read and write file as expected.

So is there anything i can do to make it work?  

My python and wasm demo:
https://github.com/bingo-V/wasmtime-py/blob/test/examples/write_file.py

**Comment by alexcrichton** [comment]
Wasmtime has [defined tiers of support for platforms](https://docs.wasmtime.dev/stability-tiers.html) which currently don't mention Android. Compilation for Android has worked in the past (and probably works now) but no regular testing is done. In that sense if you're curious to get it working on Android you're likely to run into issues but at least I personally can't be of much help as I don't have much experience running on the platform. Reading over this issue for example I don't have a clue as to what the issue might be.

That being said if you're able to diagnose PRs are of course welcome for fixing support on other platforms!

**Comment by bingo-V** [comment]
Really thanks for your reply. I will PR if i can make it.
