### ISSUE TITLE
wasmtime (13.0.0) yields errors when started with Python 3.8.18

### ISSUE THREAD

**Issue by Finfalter** [bytecodealliance/wasmtime-py#196]
Currently, I use [wasmtime 13.0.0](https://pypi.org/project/wasmtime/13.0.0/). As far as I understand, it is supposed to work with Python 3.8. However, when I try to run my application based on Python 3.8.18 it yields an error:

### Screenshot from wasmtime._module.py
![wasmtime13-error](https://github.com/bytecodealliance/wasmtime-py/assets/1852934/6acb0f5b-8c20-4e4b-aec6-152e7a98f320)

### Console view:
```bash
../../../miniconda3/envs/[..]/lib/python3.8/site-packages/wasmtime/__init__.py:23: in <module>
    from ._module import Module
../../../miniconda3/envs/[..]/lib/python3.8/site-packages/wasmtime/_module.py:9: in <module>
    class Module:
../../../miniconda3/envs/[..]/lib/python3.8/site-packages/wasmtime/_module.py:11: in Module
    def from_file(cls, engine: Engine, path: str | bytes | PathLike) -> "Module":
E   TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Comment by alexcrichton** [comment]
Thanks for the report! This was additionally discussed in https://github.com/bytecodealliance/wasmtime-py/issues/189 which has some more background. Can you try 13.0.2 or 14.0.0 and see if it works?

**Comment by Finfalter** [comment]
Thanks! Sorry that I missed that conversation. Yes, with, for example, 14.0.0, it works.
