### ISSUE TITLE
Import Order for Multiple Functions

### ISSUE THREAD

**Issue by christian512** [bytecodealliance/wasmtime-py#198]
I followed the example (shown in the [`Readme.md`](https://github.com/bytecodealliance/wasmtime-py/blob/main/examples/hello.py) and [`examples/hello.py`](https://github.com/bytecodealliance/wasmtime-py/blob/main/examples/hello.py)) to import Python functions into a module. 

As a next step, I want to import multiple Python functions into the moduleby instantiating with 
```
instance = instance = Instance(store, module, [func_hello1, func_hello2, func_hello3])
```

From my code example (see below), I expect that the output would be ordered like: 

```
Hello from Python1!
Hello from Python2!
Hello from Python3!
``` 

Instead I get a mixed output:

```
Hello from Python2!
Hello from Python3!
Hello from Python1!
```

Is the linking of multiple functions done in another way or what is causing the different order?

Below is the Python code I use to compile and run the module.
```
from wasmtime import Store, Module, Instance, Func, FuncType
 
store = Store()
module = Module(store.engine, """
  (module
    (func $hello1 (import "env" "hello1"))
    (func $hello2 (import "env" "hello2"))
    (func $hello3 (import "env" "hello3"))
    (func (export "run") (
        call $hello1
        call $hello2
        call $hello3
    ))
  )
""")
 
def hello1():
    print("Hello from Python1!")
 
def hello2():
    print("Hello from Python2!")
 
def hello3():
    print("Hello from Python3!")

func_hello1 = Func(store, FuncType([], []), hello1)
func_hello2 = Func(store, FuncType([], []), hello2)
func_hello3 = Func(store, FuncType([], []), hello3)
 
instance = Instance(store, module, [func_hello1, func_hello2, func_hello3])
 
run = instance.exports(store)["run"]
run(store)
```

**Comment by alexcrichton** [comment]
Thanks for the report! Everything works as you'd expect but the problem here is a bit subtle. The s-expression syntax you're using is what's tripping up this example. Your input module, when printed via `wasm-tools print`, will print this for example:

```wasm
(module
  (type (;0;) (func))
  (import "env" "hello1" (func $hello1 (;0;) (type 0)))
  (import "env" "hello2" (func $hello2 (;1;) (type 0)))
  (import "env" "hello3" (func $hello3 (;2;) (type 0)))
  (func (;3;) (type 0)
    call $hello2
    call $hello3
    call $hello1
  )
  (export "run" (func 3))
)
```

You'll notice here the `call` instructions aren't in the same order that you listed. The reason for that is the parentheses that you're using. The body of a function doesn't need extra parentheses so you'll want to use this instead:


```wasm
  (module
    (func $hello1 (import "env" "hello1"))
    (func $hello2 (import "env" "hello2"))
    (func $hello3 (import "env" "hello3"))
    (func (export "run") 
        call $hello1
        call $hello2
        call $hello3
    )
  )
```

**Comment by christian512** [comment]
Thanks @alexcrichton for the help. This solved my issue.
