### ISSUE TITLE
Implementing an interposer

### ISSUE THREAD

**Issue by whitequark** [bytecodealliance/wasmtime-py#2]
I wanted to use wasmtime-py to implement a tool similar to `ltrace` that intercepts WASI calls. Here's the key part of my code:
```python
def trace(name, orig):
	def trace_fn(*args):
		rets = orig(*args)
		print("{}{!r}->{!r}\n".format(name, args, rets))
		return rets
	return trace_fn
wasi = wasmtime.WasiInstance(store, "wasi_snapshot_preview1", wasi_cfg)
imports = []
for import_ in module.imports():
	if import_.module() == "wasi_snapshot_preview1":
		export = wasi.bind(import_)
		import_type = import_.type().func_type()
		wrapper = wasmtime.Func(store, import_type, trace(import_.name(), export))
		imports.append(wrapper.as_extern())
instance = wasmtime.Instance(module, imports)
instance.get_export("_start")()
```

However, this crashes almost instantly with a nested trap. I *think* this happens because the WASI implementation is internally using something like `access_caller=True` in order to access the memory, since the pointer-like WASI arguments are just indexes into that. But it seems like there's no way to pass the `Caller` along.

Is there a good way to implement such functionality regardless?

**Comment by sunfishcode** [comment]
I agree; it would be good to have a way to do this. Eventually, interface types should solve this, as they'll hopefully allow WASI functions to pass data around without exporting their linear memories and passing around offsets.

Do the wasmtime-py bindings include `env_logger`, or any way to set the `log` level? If so, Wasmtime supports an `ltrace`-like debugging facility if you set the `wasi_common` crate `log` level to `trace`, such as via the `RUST_LOG=wasi_common=trace` environment variable with `env_logger`, in case that would help.

**Comment by alexcrichton** [comment]
I don't believe the C API currently ever initializes the `log` levels, but that seems plausible to add! I'll file a PR for that

**Comment by whitequark** [comment]
I think this can be closed since calls can be traced just fine with a logger now.

**Comment by alexcrichton** [comment]
Ok!
