### ISSUE TITLE
Easy way to get version wasmtime-py

### ISSUE THREAD

**Issue by womeier** [bytecodealliance/wasmtime-py#225]
I'd like to do sth. like the following (which is not supported):

```
import wasmtime
print(wasmtime.__version__)
```

How should this best be done?
It seems, wasmtime-py uses the wasmtime binary found in the `PATH`, so shall I just run `wasmtime --version`?

**Comment by alexcrichton** [comment]
I don't think there's an easy way to do this as-is, but I think it'd be reasonble to support this. The wasmtime-py package doesn't use the `wasmtime` CLI at all, it uses support via a precompiled shared library. Implementing this would probably involve scraping information at build-time and generating some small Python source code.

**Comment by womeier** [comment]
thanks @alexcrichton, so I'll use the version pip gives me for the package.
Feel free to close this.

**Comment by alexcrichton** [comment]
Ok sounds good
