### ISSUE TITLE
pip now downloads windows binaries on alpine x64

### ISSUE THREAD

**Issue by 2-www** [bytecodealliance/wasmtime-py#239]
### Steps to Reproduce
`pip install wasmtime`
### Expected Results
either working wasmtime, or an error "No matching distributions found" like in bytecodealliance/wasmtime#995
### Actual Results
it appears to succeed, but it actually downloads a windows library (/usr/local/lib/python3.12/site-packages/wasmtime/win32-x86_64/_wasmtime.dll)
### Versions and Environment
Operating system: alpine linux
Architecture: x86_64

**Comment by alexcrichton** [comment]
Thanks for the report! I've transferred this to the wasmtime-py repository which contains the Python bindings you're referring to. I also believe that this is a duplicate of https://github.com/bytecodealliance/wasmtime-py/issues/237 and will be resolved with Wasmtime 22 to be released on June 20.
