### ISSUE TITLE
Type annotations for method signatures

### ISSUE THREAD

**Issue by tobych** [bytecodealliance/wasmtime-py#24]
I'd like to see type annotations throughout the code, especially in function and method signatures, so I can see what's needed where, and so users and other developers will be able to see what's needed where. Sphinx (for generating documentation) can, if we're lucky, use these when it's showing the signature of methods.

I've gone through and done this in the code, but the commit isn't ready yet and I wanted to to see if https://github.com/bytecodealliance/wasmtime-py/pull/17 would be merged, if at all, as I might need to make a case for this ticket just as I do for that one.

I also drew a big diagram of all the classes, using [PlantUML](https://plantuml.com/), as I went. Doing these at the same time is, I find, usually a very sensible idea. It took quite a bit a work to figure out what was needed where, including much use of the debugger. I think there's a new Python tool to help do this that Guido worked on, but I find that doing it manually makes for a good way of getting to know the code.

**Comment by whitequark** [comment]
I would be very happy to see type annotations in signatures as they have virtually no cost and are a major improvement in accessibility, especially when using IDEs, but in the documentation as well.

**Comment by alexcrichton** [comment]
I'd be more than happy to merge these in!

**Comment by tobych** [comment]
Here's the diagram I mentioned above. Work in progress.

![image](https://user-images.githubusercontent.com/175174/82964756-1cba8100-9f7b-11ea-8329-aab89da9cd56.png)
