### ISSUE TITLE
`TypeError: WasiConfig.preopen_dir() missing 2 required positional arguments: 'dir_perms' and 'file_perms'`

### ISSUE THREAD

**Issue by whitequark** [bytecodealliance/wasmtime-py#259]
Since the release of wasmtime-py 27.0.0 my builds started [failing](https://github.com/amaranth-lang/amaranth-yosys/actions/runs/11944284355/job/33294963907) with:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/amaranth-yosys/amaranth-yosys/amaranth_yosys/__main__.py", line 16, in <module>
    wasi_cfg.preopen_dir(".", ".")
TypeError: WasiConfig.preopen_dir() missing 2 required positional arguments: 'dir_perms' and 'file_perms'
```

Is this an intentional compatibility break?

**Comment by whitequark** [comment]
Also, I'm pretty sure this is inheriting the wrong class:

```
class wasi_dir_perms_flags(Enum):
```

Rather than `enum.Enum` it should be `enum.Flags` (or `enum.IntFlags`)

**Comment by alexcrichton** [comment]
It's intended in the sense that the new arguments were added, but I also think it'd be reasonable to make these arguments have default values as well which I think would keep things backwards-compatible?

In general this project isn't in a position though to provide a 100% guarantee of backwards-compat, but I'm certainly happy to help out with updates to fix any issues like this though of course.

**Comment by whitequark** [comment]
> I also think it'd be reasonable to make these arguments have default values as well which I think would keep things backwards-compatible?

That sounds great. Not having backwards-compat doesn't *entirely break* my use case but it introduces fragmentation in wasmtime versioning that causes downstream version conflicts that are very frustrating for end users to resolve (sometimes, impossible). It is the kind of thing people quit an ecosystem because of (Python packaging is kind of a sore point in general), which is why I pay extra attention to it.

**Comment by whitequark** [comment]
> Also, I'm pretty sure this is inheriting the wrong class:
> 
> ```
> class wasi_dir_perms_flags(Enum):
> ```
> 
> Rather than `enum.Enum` it should be `enum.Flags` (or `enum.IntFlags`)

After a second round of review I realized that there are two enums like this and the one exposed to the end user is:

```
class DirPerms(Enum):
```

which doesn't have the problem where it is a flag enum but can't be combined using `|`. So please disregard it.

**Comment by alexcrichton** [comment]
I'll merge/tag https://github.com/bytecodealliance/wasmtime-py/pull/260 once it's ready, and yeah was gonna come here to confirm the enum/flags thing as well but sounds good 👍 

I'll try to be on the lookout in the future for API-breaking changes.

**Comment by whitequark** [comment]
> I'll try to be on the lookout in the future for API-breaking changes.

I appreciate this, but please don't feel pressure to. I have scripts that robustly and quickly detect at least the kind of breakage that affects my software (as seen here), so it's something that isn't difficult to resolve and has little impact on end users if it is.

Are you going to release 27.0.1 or 27.1.0? Either way, I'd like to request yanking the non-backwards-compatible version, otherwise it becomes a valid version resolution target and you have to carry it forever as a `!=27.0.0` dependency which is a bit burdensome.
