### ISSUE TITLE
Caching compiled code

### ISSUE THREAD

**Issue by whitequark** [bytecodealliance/wasmtime-py#3]
At the moment it seems that even though wasmtime itself implements a very nice caching system that makes startup latency almost disappear in my application, wasmtime-py does not use it. Is this intentional, or is this just an oversight?

For now I was able to work around that with an intrusive patch that cuts down the application size to under 2 MB, which takes about 2 seconds to compile on a modern laptop, but that's a pretty significant limitation and I'm worried about the increase in latency on low-end hardware.

**Comment by alexcrichton** [comment]
Turns out this actually isn't possible today with the C API, so I've opened up https://github.com/bytecodealliance/wasmtime/pull/1606 to start the process of getting that upstream here.

**Comment by whitequark** [comment]
Thank you!
