### ISSUE TITLE
Handling the exit trap

### ISSUE THREAD

**Issue by whitequark** [bytecodealliance/wasmtime-py#30]
Since wasmtime-py 0.18.0, it seems that when the `main()` function returns, the call to `_start()` also simply returns, which is good. However, it looks like if `exit()` is called, then the result is a `wasmtime._trap.Trap: Exited with i32 exit status 1`. It is not clear how this trap can be handled besides matching the exception message with a regex.

**Comment by whitequark** [comment]
It looks like I am mistaken; the only change in behavior is that nonzero exit codes result in a trap now. That's great, actually! But I'd still need some nice way to handle the trap.

**Comment by whitequark** [comment]
After more testing I think my original conclusion was accurate; I later dismissed it because wasmtime 0.17 had another issue, which is that it looks like setting argv doesn't work at all.

**Comment by alexcrichton** [comment]
Ah yes, I'll add C API functions for inspecting this so a new exception class can be implemented here.

**Comment by alexcrichton** [comment]
Ok I've added bindings for this at https://github.com/bytecodealliance/wasmtime-py/pull/35
