### ISSUE TITLE
Exit traps crash on Windows with STATUS_BAD_STACK

### ISSUE THREAD

**Issue by whitequark** [bytecodealliance/wasmtime-py#36]
Original report at https://github.com/YoWASP/yosys/issues/1.

To reproduce the crash, do the following on Windows x64 with Python installed:
  * `pip3 install yowasp-yosys`
  * `yowasp-yosys -V`

I haven't personally verified it but I believe that any program that consists of just `exit(0);` will exhibit the same issue. Let me know if you'd like to have this minimized further or if this is sufficient.

**Comment by alexcrichton** [comment]
Hm I unfortunately can't reproduce the crash on my Windows machine. That command ends up printin `Yosys 0.9+2406 (git sha1 8c4cb188, ccache clang 9.0.0-2~ubuntu18.04.2 -Os -flto -flto)` (pretty slow the first time, reasonably fast the second time)

I'm using Python 3.8.3 from the msys2 packages, perhaps you're using a different Python?

**Comment by whitequark** [comment]
> That command ends up printin `Yosys 0.9+2406 (git sha1 8c4cb188, ccache clang 9.0.0-2~ubuntu18.04.2 -Os -flto -flto)` (pretty slow the first time, reasonably fast the second time)

That's the expected behavior, but afterwards it also displays a crash dialog and returns a non-zero errorlevel (in fact it returns `0xc0000028`). Is the errorlevel 0 for you? Perhaps the crash dialog is somehow suppressed.

My Python is from `python.org`, with this version string:

```
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
```

**Comment by alexcrichton** [comment]
Aha apparently my msys/mingw prompt was hiding that, but it is indeed exiting with 127. I'll try to dig in from there, thanks!

**Comment by alexcrichton** [comment]
Ok I've moved this over to https://github.com/bytecodealliance/wasmtime/issues/1967, will keep trying to reduce to see what's going on!

**Comment by whitequark** [comment]
Now that this is fixed, can I get a new wasmtime-py release please?

**Comment by alexcrichton** [comment]
Sure thing! I've pushed a tag and it should be [published from CI soon](https://github.com/bytecodealliance/wasmtime-py/actions/runs/162034031)

**Comment by whitequark** [comment]
I've confirmed it works. Once again, awesome work!
