### ISSUE TITLE
Querying the cache

### ISSUE THREAD

**Issue by whitequark** [bytecodealliance/wasmtime-py#37]
Especially for larger applications, the cold startup time can be quite long. As a result people end up unsure whether the application is compiling or just hung. It would be nice if there was some way to check if I'm about to hit the cache, so that if I'm going to miss, I could print a message of some sort to stderr.

**Comment by alexcrichton** [comment]
Makes sense to me! I think with a feature like https://github.com/bytecodealliance/wasmtime/issues/1779 we may be able to support this well where caching will be first-class at that point rather than hidden behind the scenes. In any case this'll need to be implemented upstream in Wasmtime first.

**Comment by whitequark** [comment]
Cool, looking forward to it. I'm very happy with wasmtime managing the caching for me though.

**Comment by alexcrichton** [comment]
With `Module.deserialize` and `Module.serialize` I think that this is "effectively done" in that it enables building the cache externally if this is desired. I don't think we're going to add more intrusive support for the built-in cache in Wasmtime itself given this feature as well.

**Comment by whitequark** [comment]
> With `Module.deserialize` and `Module.serialize` I think that this is "effectively done" in that it enables building the cache externally if this is desired.

I've already done this so closing this is completely reasonable.
