### ISSUE TITLE
Python idioms in the API

### ISSUE THREAD

**Issue by whitequark** [bytecodealliance/wasmtime-py#4]
The README mentions that:

> So far this extension has been written by folks who are primarily Rust programmers, so it's highly likely that there's some faux pas in terms of Python idioms. Feel free to send a PR to help make things more idiomatic if you see something!

Indeed, after using the API for a while I noticed a few aspects that aren't quite in line with Python conventions, though some of them are harder to ignore than others.

  1. Nullary getter methods like `ExportType.name` that always succeed and always return the same value are a pretty clear-cut case for using Python properties instead. This is, by far, the least idiomatic aspect of the library, and it's very easy to miss a `()` that feels like it shouldn't be there.
  2. There are lots of unary setter methods like `Config.debug_info` named after the property they're changing, and there is a good case for using Python setter-only properties instead. (As a bonus, if wasi-c-api ever adds getters for them, they could be made readable in a backwards compatible way.) This doesn't change much for e.g. `Config`, but for `Linker` for example `allow_shadowing` works like a simple setter with no side effects, but `define_wasi`, while similarly imperatively named and used, irreversibly changes its state.
  3. Nullary casting methods like `ExternType.func_type` feel very odd overall.
    1. They're named like accessors, but they work like `dynamic_cast`.
    2. The naming is inconsistent for conversion in different directions—`FuncType`→`ExternType` conversion is done by `as_extern`, but `ExternType`→`FuncType` conversion is performed by `func_type`.
    3. My impression so far is that most uses of these casting methods are in contexts where a specific type is expected, in which case it would be more convenient if they raised `TypeError` instead of returning `None`. (If they did, another method would be necessary to dispatch on an unknown type.)
  4. `Val.get_*` introduces a third naming scheme for type conversion functions, one that clashes in meaning with e.g. `Instance.get_export`.
  5. `*.get_export()` methods seem like they would only fail in truly exceptional conditions and so also appear good candidates for raising an exception instead of returning `None`.

To summarize:
  1. I would change simple getters and setters to be properties.
  2. I would rename all casting methods to `as_*()`.
  3. I would change `*.get_export()` to raise if the export is not found (this is particularly important for `Caller.get_export()`, since currently it looks like there is no way to distinguish the cases of "export does not exist" and "the caller is gone" at all, even for debugging, and the exception message would allow that).
  4. I would *probably* change the dynamic casting methods to raise if the type is wrong, and add a matching `is_*` method for the cases where dynamic dispatch is indeed necessary. I'm not completely certain about this one, but it seems that currently, dynamic dispatch would look something like:
   ```python
   if extern.memory():
       do_something_with_memory(extern.memory())
   elif extern.table():
       do_something_with_table(extern.table())
   ```
   so changing it to:

   ```python
   if extern.is_memory():
       do_something_with_memory(extern.as_memory())
   elif extern.is_table():
       do_something_with_table(extern.as_table())
   ```

   doesn't really make it any worse.

What do you think? All of these changes are likely to break most existing code, so I'd rather discuss them before working on a PR.

Also, I should mention that "do nothing" is an option. In general Python libraries are a lot looser with conventions than libraries in many other languages; I'd rather see the API improved, personally, but the current one isn't drastically more inconsistent than what one would expect in general.

**Comment by plicease** [comment]
I'm working on the Perl bindings for wasmtime which is based heavenly on `wasmtime-py`, and I'm not a Python programmer, but my unsolicited thoughts:

 1. I like the idea of renaming the casting functions to have a consistent `as_` prefix, in fact this is mostly how I implemented for my Perl bindings.  It also more closely resembles the c-api, so familiarity with one is helpful for the other.

 2. I also like having the `is_` methods, I think that helps the reader understand the intent of what you are doing.  In Perl I have `kind` and `kind_num` methods that wrap around the c-api, which gets you this same information, but the cost there is either converting to a string, or exporting constants.

 3. I'm not as sure about `get_export` raising an exception, to me it makes sense for `None` (or `undef` in my case) to be returned when you ask for something that doesn't exist.  It would make chaining more sensible though `.get_export("foo").as_func().call()` doesn't try to call `as_func` on `None`.  I'm uneasy about this one though because again, I'm not a Python programmer, and I haven't even tried to build `wasmtime-py`, just my opinion based on implementing `get_export` in Perl.

It's cool to have a similar project in another scripting language to crib off of.

**Comment by whitequark** [comment]
> 3\. I'm not as sure about `get_export` raising an exception, to me it makes sense for `None` (or `undef` in my case) to be returned when you ask for something that doesn't exist.

This is actually an established and widespread Python idiom called [EAFP](https://docs.python.org/3/glossary.html#term-eafp). Personally, I follow it very cautiously; for example, dictionary indexing raising `KeyError` *that you are supposed to catch* is a source of subtle bugs because the `try: except:` construct is unwieldy and it is tempting to put something besides the index operation itself in the `try:` expression, but of course now you may have caught an exception raised by third party code that should have bubbled up.

In this case however, assuming my intuition about the use of `.get_export()` is correct--that the vast majority of invocations are likely to succeed, and failures indicate logic errors--it seems like a solid case for that idiom. Consider that it would work much like the built-in dictionaries.

**Comment by alexcrichton** [comment]
These all sound like great ideas to me, I think a PR would be great!

It's probably possible to simply remove all casts entirely, we can probably do dynamic type checks to figure everything out at the API layer.

@whitequark did you want to work on a PR for this? If not I can try to whip something up myself.

**Comment by whitequark** [comment]
> did you want to work on a PR for this? If not I can try to whip something up myself.

Please feel free to do so, my hands are quite full :)

**Comment by whitequark** [comment]
Ah, maybe this will save you a bit of time--the way you can make a setter-only property in Python is not obvious. This works:

```python
setter_property = lambda fset: property(fset=fset)
class foo:
    @setter_property
    def bar(self, value):
        print(value)
foo().bar = 1 # 1
foo().bar # AttributeError: unreadable attribute
```

**Comment by alexcrichton** [comment]
Ok I've opened up https://github.com/bytecodealliance/wasmtime-py/pull/5 which covers points 1/2/4 from [your summary above](https://github.com/bytecodealliance/wasmtime-py/issues/4#issue-607646400).

Like @plicease though I'm a little hesitant to raise an exception from `get_export` (on both `Instance` and `Caller`). Is there perhaps a way to have both though? Is it possible to do something like:

```python
instance.exports.foo # raises if invalid
instance.get_export("foo") # returns None if invalid
```

**Comment by whitequark** [comment]
> Is there perhaps a way to have both though?

There are a few ways. Regarding your suggestion,

> ```python
> instance.exports.foo # raises if invalid
> ```

in my opinion this is not an appropriate place to override `__getattr__`. There are a number of issues with such an override, chiefly, name clashes (adding another method to that class becomes a breaking change), the need to use `getattr` or `__getattr__` if the identifier is non-alnum or has interpolations, and the ambiguity in an expression like `instance.exports.memory`--can you say whether the name "memory" reserved and provided by wasmtime, or available for use and provided by the instance?

I have two proposals. The first is to remove `get_export` entirely and provide an `exports` object that behaves like a normal Python dict:

```python
instance.exports["foo"] # KeyError: "foo" if invalid
instance.exports.get("foo") # is None if invalid
```

For `Instance` this would require replacing the existing `exports` property that returns a list with one that returns a proxy object indexable by either an `int` or a `str`, and iterable in the same way it currently is. One additional benefit of this approach is that doing something like `instance.exports[n]` in a loop becomes much cheaper than it is now.

For `Caller` this would require adding a new `exports` property that returns *another* proxy object, this time indexable only with a `str`.

The second proposal is adding an optional default value to `get_export`. (The `dict.get()` method has one.)

```python
instance.get_export("foo") # raises if invalid
instance.get_export("foo", default=None) # returns None if invalid
```

I think either solution is fine, but I somewhat prefer the first one. It is more involved to implement though.

**Comment by alexcrichton** [comment]
That sounds like a great suggestion to me! -- #6

**Comment by whitequark** [comment]
Thanks for the fix!
