### ISSUE TITLE
qjs.wasm loops forever

### ISSUE THREAD

**Issue by Hywan** [bytecodealliance/wasmtime-py#49]
Hello,

I'm trying to run `qjs.wasm` with `wasmtime-py`. The compilation step works great, but the execution loops forever, and I don't know why. We quickly tried to debug that with @bnjbvr with no obvious solution so far.

You can get `qjs.wasm` from https://wapm.io/package/quickjs#explore. Here is the test script.

```py
import wasmtime

TEST_BYTES = open('qjs.wasm', 'rb').read()

config = wasmtime.Config()
config.strategy = 'auto'
engine = wasmtime.Engine(config)
store = wasmtime.Store(engine)

wasi_config = wasmtime.WasiConfig()
wasi_config.argv = ['--help']
wasi = wasmtime.WasiInstance(store, 'wasi_unstable', wasi_config)

module = wasmtime.Module(wasi.store.engine, TEST_BYTES)

imports = []

for import_ in module.imports:
    imports.append(wasi.bind(import_))

instance = wasmtime.Instance(store, module, imports)

a = instance.exports["_start"]
a()
```

**Comment by alexcrichton** [comment]
I believe the bug here is that the wasi stdin/stdout/stderr is all disabled. You'll need to call `.inherit_std{in,out,err}()` as appropriate. Additionally I believe the argv neeeds to be `qjs --help` to work, just `--help` brings up the JS prompt for me.

**Comment by Hywan** [comment]
Awesome, thanks!
