### ISSUE TITLE
Env variables are not being passed to WASM

### ISSUE THREAD

**Issue by kesmit13** [bytecodealliance/wasmtime-py#74]
I'm not having any success getting environment variables in the WASM environment. My code is below. There is a function written in C compiled to WASM that does a `getenv("FOO")` which is `NULL`. I've also tried using `wasi.inherit_env()`, but that doesn't work for me either. 

```
import os
import struct
import sys
import wasmtime
from bindings import Udf

store = wasmtime.Store()

module = wasmtime.Module(store.engine, open('funcs.wasm', 'rb').read())

linker = wasmtime.Linker(store.engine)
linker.define_wasi()

wasi = wasmtime.WasiConfig()

# Set mounts
wasi.preopen_dir(os.path.join(os.getcwd()), '/')

# Set stdin / stdout / stderr
wasi.inherit_stdin()
wasi.inherit_stdout()
wasi.inherit_stderr()

# Set command-line args
wasi.argv = ['python']

# Set environment variables
wasi.env = dict(FOO='bar').items()

store.set_wasi(wasi)

udf = Udf(store, linker, module)
udf.call_function(store)
```

**Comment by kesmit13** [comment]
As a point of comparison, the environment variables work fine when using the `wasmtime` cli.

**Comment by alexcrichton** [comment]
Thanks for the report. I've tried this out locally and can't immediately reproduce it. Can you share some more information such as the wasm source, the toolchain you used to produce the wasm source, and this library's version?

**Comment by kesmit13** [comment]
I figured out what's happening. The `_initialize` export isn't getting called. I'm using the witx/wai wrappers which don't give you direct access to `_initialize` so I figured it was being called automatically, but that was not the case.
