### ISSUE TITLE
how to compile application to wasi?

### ISSUE THREAD

**Issue by fengqi2019** [bytecodealliance/wasmtime-py#75]
hello, how can i compile pyhon's application to wasi?

**Comment by alexcrichton** [comment]
Can you provide some more detail as to your question? Are you trying to compile Python to WebAssembly? Or are you trying to use this dependency? Or perhaps something else altogether?

**Comment by fengqi2019** [comment]
i want to know is it posible to compile Python to wasi(WebAssembly System Interface)? then i learn more infomation, find the answer is no. right?

**Comment by alexcrichton** [comment]
I believe right now it's not possible to do so without modifying the Python source. I know some folks are working on making this easier, but that's also not what this repository is for. This repository is a Python embedding of Wasmtime which is for native Python applications to execute WebAssembly code using Wasmtime.

**Comment by fengqi2019** [comment]
ok,thank you for your answer.
