### ISSUE TITLE
[question?] Is it possible to pass a borrowed list from Python?

### ISSUE THREAD

**Issue by freedeaths** [bytecodealliance/wasmtime-py#78]
I wrote a lib with Rust, who has a function as below:

``` rust
#[no_mangle]
pub fn cpd(signal: &[f64], jump: usize, p_value: f64, permutations: usize) -> Vec<usize> {
    //...
}
```

I compiled it to wasm32-wasi, and call `cpd` function from Python:

1. I tried as below and got an error, which said `wasmtime._error.WasmtimeError: too few parameters provided: given 4, expected 6`

```python
import wasmtime.loader
import mylib

a = [1.,2.,3.,4.,5.]

print(mylib.cpd(a, 5, 0.05, 1000))
```

2. Then I found this information `Exports: Functions: "cpd": [I32, I32, I32, I32, F64, I32] -> []`. I guess &[f64] may be converted to a fat pointer. But the code below didn't work too and got en error as `wasmtime._trap.Trap: wasm trap: out of bounds memory access`

```python
import wasmtime.loader
import mylib

a = [1.,2.,3.,4.,5.]

address = id(a)
length = len(a)
capacity = length

print(mylib.cpd(address, length, capacity, 5, 0.05, 1000))
```

### Question

So are there any ideas to solve this problem? TIA

**Comment by alexcrichton** [comment]
No this won't work natively as you'd expect, when calling a function all that happens is that the parameters are passed by-value to wasm. To pass something like a list you'd need to modify the contents of the linear memory of the wasm module. This is unfortunately a pretty involved process today. The goal of the interface-types proposal, coupled with [`wit-bindgen`](https://github.com/bytecodealliance/wit-bindgen), is to make these issues much easier.

**Comment by freedeaths** [comment]
Thank you very much for your information, Alex. I will take a look at `wit-bindgen`.
