### ISSUE TITLE
wasmtime arm64 wheel for mac m1

### ISSUE THREAD

**Issue by pannous** [bytecodealliance/wasmtime-py#79]
Even though arm support has landed a year ago (https://github.com/bytecodealliance/wasmtime/issues/339), it seems it has not found its way into a macOS AArch64 pip wheel:
```
Successfully installed wasmtime-0.33.0

from wasmtime import *

"unsupported architecture for wasmtime: arm64"
```

(macOS Monterey 12.1 M1, Python 3.8.9)

**Comment by pannous** [comment]
Usually issues are closed once they are resolved?

**Comment by whitequark** [comment]
@alexcrichton There are precompiled binaries now; could you reopen this, please?

**Comment by alexcrichton** [comment]
Sure thing

**Comment by igrr** [comment]
I have opened a draft PR https://github.com/bytecodealliance/wasmtime-py/pull/92 for macOS arm64 support.
