### ISSUE TITLE
What's the difference between this and wasmer?

### ISSUE THREAD

**Issue by chaosprint** [bytecodealliance/wasmtime-py#86]

**Comment by alexcrichton** [comment]
This Python packaged is implemented with the [Wasmtime](https://github.com/bytecodealliance/wasmtime) wasm runtime, while I presume that the wasmer Python package is probably implemented with wasmer.

If you're curious about comparing the two engines themselves I'd recommend you take a look at both and explore, I'm not personally in a position to advise you one way or another.
