### ISSUE TITLE
AttributeError: unreadable attribute

### ISSUE THREAD

**Issue by smpurkis** [bytecodealliance/wasmtime-py#91]
Hello,

I'm getting this error (full traceback)
```
Traceback (most recent call last):
  File "main_wasmtime.py", line 4, in <module>
    config.wasm_multi_memory(True)
AttributeError: unreadable attribute
```

when I run the following code:
```
from wasmtime import Config

config = Config()
config.wasm_multi_memory(True)
config.wasm_threads(True)
```

I need the threads enabled for a wasm file I'm working with, however it doesn't look like it can be set using the wasmtime-py API correctly.

My environment is:
- Python 3.9.7
- Wasmtime 0.39.1
- Ubuntu 20.04 (Linux e127538 5.13.0-44-generic 49~20.04.1-Ubuntu SMP Wed May 18 18:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux)

Am unsure how to proceed as I can't think of a workaround.

**Comment by alexcrichton** [comment]
I believe these are properties, so does `config.wasm_multi_memory = True` work instead?

**Comment by smpurkis** [comment]
That worked! Thanks very much!
